# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.URLField(blank=True, default='https://www.civilsociety.co.uk/assets/img/user-img-lg.jpg', null=True)),
                ('horario', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.URLField(blank=True, default='https://www.civilsociety.co.uk/assets/img/user-img-lg.jpg', null=True)),
                ('crm', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.URLField(blank=True, default='https://www.civilsociety.co.uk/assets/img/user-img-lg.jpg', null=True)),
                ('cpf', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('cid', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especialista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especialista'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
    ]
