# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=200, verbose_name='Ponto de Referência')),
                ('photo', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('photo', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=30)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('coletado', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=200, verbose_name='Ponto de Referência')),
                ('descricao', models.TextField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('lat_map', models.CharField(max_length=100)),
                ('lng_map', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
