# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('DELETE_LOJA', 'DELETE_LOJA'), ('ACCEPT_ORDER', 'ACCEPT_ORDER'), ('CANCEL_ORDER', 'CANCEL_ORDER'), ('ENABLE_ROTA', 'ENABLE_ROTA'), ('ORDER_DELIVERED', 'ORDER_DELIVERED'), ('ADMIN_MESSAGE', 'ADMIN_MESSAGE'), ('ALL_DELIVERED', 'ALL_DELIVERED')], max_length=100),
        ),
    ]
