# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'permissions': (('view_dashboard_1', 'Loja pode ver o dashboard loja tipo 1'), ('view_dashboard_2', 'Loja pode ver o dashboard loja tipo 2'), ('view_dashboard_3', 'Loja pode ver o dashboard loja tipo 3'), ('view_chat', 'Loja pode interagir no Chat'))},
        ),
    ]
