# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
