# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('warning', 'warning'), ('danger', 'danger')], max_length=100),
        ),
    ]
