# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171225_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(default='', max_length=100),
        ),
    ]
