# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_motorista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='placa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
