# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171212_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificacao',
            new_name='Notification',
        ),
    ]
