# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171225_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
