# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='cep',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
    ]
