# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171226_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
