# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171212_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
