# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171226_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Salvar como Rascunho'),
        ),
    ]
