# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171213_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='full_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='full_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('DELETE_LOJA', 'DELETE_LOJA'), ('ACCEPT_ORDER', 'ACCEPT_ORDER'), ('CANCEL_ORDER', 'CANCEL_ORDER'), ('ENABLE_ROTA', 'ENABLE_ROTA'), ('ORDER_DELIVERED', 'ORDER_DELIVERED')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
