# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171230_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
