# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171214_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
