# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180104_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('is_feriado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('tema', models.CharField(blank=True, choices=[('BLACK', 'skin-black')], default='skin-black', max_length=100, null=True)),
                ('plano', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bairro',
            name='valor_feriado',
            field=models.CharField(default='9', max_length=3),
        ),
        migrations.AddField(
            model_name='bairro',
            name='valor_madrugada_feriado',
            field=models.CharField(default='11', max_length=3),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Configuration'),
        ),
    ]
