# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171215_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('DELETE_LOJA', 'DELETE_LOJA'), ('ACCEPT_ORDER', 'ACCEPT_ORDER'), ('CANCEL_ORDER', 'CANCEL_ORDER'), ('ENABLE_ROTA', 'ENABLE_ROTA'), ('ORDER_DELIVERED', 'ORDER_DELIVERED'), ('ALL_DELIVERED', 'ALL_DELIVERED')], max_length=100),
        ),
    ]
