# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180105_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='plano',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=100),
        ),
    ]
