# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180105_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tema',
            field=models.CharField(blank=True, choices=[('BLACK', 'skin-black'), ('BLUE', 'skin-blue'), ('RED', 'skin-red'), ('YELLOW', 'skin-yellow'), ('PURPLE', 'skin-purple'), ('GREEN', 'skin-green')], default='skin-black', max_length=100, null=True),
        ),
    ]
