# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180108_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='complemento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ponto de Refer\xeancia'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endere\xe7o'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='complemento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ponto de Refer\xeancia'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='complemento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ponto de Refer\xeancia'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endere\xe7o'),
        ),
    ]
