# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='placa',
            field=models.CharField(default='PKG-0099', max_length=30),
            preserve_default=False,
        ),
    ]
