# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180130_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
