# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_ponto_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configadmin',
            name='end_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configadmin',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configadmin',
            name='start_promo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
