# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_motorista_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
