# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180213_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Configuration'),
        ),
    ]
