# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_estabelecimento_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='nome_cliente',
        ),
    ]
