# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20171219_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='bairro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='bairro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro'),
        ),
    ]
