# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ponto_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_cozinha',
            field=models.BooleanField(default=False),
        ),
    ]
