# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_pedido_status_cozinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='has_cozinha',
            field=models.BooleanField(default=False),
        ),
    ]
