# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_ponto_is_prepared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nota', models.CharField(max_length=2)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido')),
            ],
            options={
                'verbose_name': 'Avalia\xe7\xe3o',
                'verbose_name_plural': 'Avalia\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, default='', max_length=12, null=True, unique=True)),
                ('foto', models.URLField(blank=True, default='http://placehold.it/100x100', null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_completo', models.CharField(blank=True, max_length=300, null=True)),
                ('valor_entrega', models.CharField(blank=True, default='6', max_length=3, null=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(blank=True, choices=[('VOU BUSCAR', 'VOU BUSCAR'), ('MOTOBOY', 'MOTOBOY')], default='MOTOBOY', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Forma de Entrega',
                'verbose_name_plural': 'Formas de Entrega',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(blank=True, choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO'), ('DINHEIRO', 'DINHEIRO'), ('REFEICAO', 'REFEICAO')], default='DINHEIRO', max_length=100, null=True)),
                ('cartao', models.CharField(blank=True, choices=[('MASTERCARD', 'MASTERCARD'), ('VISA', 'VISA'), ('ELO', 'ELO'), ('VR', 'VR'), ('HIPERCARD', 'HIPERCARD'), ('SODEXO', 'SODEXO')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foto de Produto',
                'verbose_name_plural': 'Foto de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('limitador', models.CharField(default='1', max_length=2)),
                ('obrigatoriedade', models.BooleanField(default=False)),
                ('tipo', models.CharField(default='radio', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.CharField(blank=True, default='1', max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('type_message', models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('ADMIN_MESSAGE', 'ADMIN_MESSAGE')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pedido')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica\xe7\xe3o',
                'verbose_name_plural': 'Notifica\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=10)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'verbose_name': 'Opcional',
                'verbose_name_plural': 'Opcionais',
            },
        ),
        migrations.CreateModel(
            name='OpcionalChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ItemPedido')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Opcional')),
            ],
            options={
                'verbose_name': 'Opcional Escolhido',
                'verbose_name_plural': 'Opcionais Escolhidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='')),
                ('preco_base', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('status_pedido', models.CharField(blank=True, choices=[('AGUARDANDO', 'AGUARDANDO'), ('ACEITO', 'ACEITO'), ('REJEITADO', 'REJEITADO'), ('PREPARANDO', 'PREPARANDO'), ('ENTREGANDO', 'ENTREGANDO'), ('ENTREGUE', 'ENTREGUE')], default='AGUARDANDO', max_length=100, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True)),
                ('troco', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('endereco_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='configadmin',
            options={'verbose_name': 'Configura\xe7\xe3o do Sistema', 'verbose_name_plural': 'Configura\xe7\xe3o do Sistema'},
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('NOTIFICACAO_COZINHA', 'NOTIFICACAO_COZINHA'), ('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('DELETE_LOJA', 'DELETE_LOJA'), ('ACCEPT_ORDER', 'ACCEPT_ORDER'), ('CANCEL_ORDER', 'CANCEL_ORDER'), ('ENABLE_ROTA', 'ENABLE_ROTA'), ('ORDER_DELIVERED', 'ORDER_DELIVERED'), ('ADMIN_MESSAGE', 'ADMIN_MESSAGE'), ('ALL_DELIVERED', 'ALL_DELIVERED'), ('LOJA_MESSAGE', 'LOJA_MESSAGE'), ('MOTORISTA_MESSAGE', 'MOTORISTA_MESSAGE')], max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='request',
            name='forma_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaEntrega'),
        ),
        migrations.AddField(
            model_name='request',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaPagamento'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='fotoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='formaentrega',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
