# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180322_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Request'),
        ),
    ]
