# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_request_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
    ]
