# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180322_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='chamar_motoboy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tempo_de_entrega',
            field=models.CharField(default=50, max_length=2),
        ),
    ]
