# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_folhapagamento_valor_cobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='resultado_troco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
