# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_request_resultado_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoproduto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
