# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180323_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='creditos_expirados',
            field=models.BooleanField(default=False),
        ),
    ]
