# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_motorista_creditos_expirados'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
