# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20180324_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BairroGratis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bairro')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Bairro Gratis',
                'verbose_name_plural': 'Bairros Gratis',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='status_entrega_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
