# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20180325_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairrogratis',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
