# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcional',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
