# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_configuration_blocked_cozinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
