# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20180326_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
