# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20180402_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='bairrogratis',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bairros_gratis', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folhas_pagamento', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='formaentrega',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_entrega', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='request',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.Estabelecimento'),
        ),
    ]
