# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20180405_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='bairrogratis',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='formaentrega',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='request',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
