# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20180405_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='valor_total',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_total',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentomotorista',
            name='valor_total',
            field=models.CharField(default='15.00', max_length=300),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='request',
            name='valor_total',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
