# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20180425_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='valor_entrega',
            field=models.TextField(blank=True, default='6', null=True),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='valor_cobrar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='valor_total',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_total',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opcional',
            name='valor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagamentomotorista',
            name='valor_total',
            field=models.TextField(default='15.00'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='valor_total',
            field=models.TextField(blank=True, null=True),
        ),
    ]
