# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20180426_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
