# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_estabelecimento_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='has_fixos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='fixo_loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
