# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20180518_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='has_fixos',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='fixo_loja',
        ),
    ]
