# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20180518_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
