# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_categoria_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='has_fixos',
            field=models.BooleanField(default=False),
        ),
    ]
