# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_configuration_has_fixos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='motoboys',
            field=models.ManyToManyField(blank=True, null=True, to='app.Motorista'),
        ),
    ]
